Nt = 3200
Nx = 101
Ny = 101
Xmin = -5.0
Xmax = 5.0
Ymin = -5.0
Ymax = 5.0

cfl = 0.1

<<<<<<< Updated upstream
id_x0 = 0.0
id_y0 = 0.0
id_sigma = 1.0
id_amp = 1.0
bound_cond = "REFLECT"
=======
id_x0 = 1
id_y0 = 1
id_sigma = 1.0
id_amp = 1
bound_cond = "SOMMERFELD"
>>>>>>> Stashed changes

output_dir = "output_sowave"
output_interval = 5